name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java-version: [8.x, 11.x, 13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java-version }}
    - name: Run a one-line script
      run: ./gradlew build
      env:
        CI: true
