name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macOS-latest]
        java-version: [8.x, 11.x, 13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java-version }}
    - name: Gradle build
      run: ./gradlew build
      env:
        CI: true
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 13.x
    - name:
      run: ./gradlew check jacocoTestReport coveralls
      env:
        CI: true
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 13.x
    - name:
      run: ./gradlew bintrayUpload
      env:
        CI: true
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
